[template]
src   = "10-syslog-central.conf.tmpl"
dest  = "/etc/rsyslog.d/10-syslog-central.conf"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "syslog"
]
check_cmd = "/bin/bash -c '/usr/sbin/rsyslogd -N1 -f {{.src}} | logger -p local0.info -t confd-10-syslog-central-check'"
reload_cmd = "/usr/local/bin/supervisorctl restart rsyslog | logger -p local0.info -t confd-10-syslog-central-reload"