[template]
src   = "rabbitmq.config.tmpl"
dest  = "/etc/rabbitmq/rabbitmq.config"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "rabbitmq"
]
reload_cmd = "/usr/local/bin/rabbitmq-reload | logger -p local0.info -t confd-rabbitmq-reload"