[template]
src   = "rabbitmq.config.tmpl"
dest  = "/etc/rabbitmq/rabbitmq.config"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "rabbitmq"
]
check_cmd = "/bin/bash -c 'echo Skip Validation... 1>/var/log/rabbitmq-check.log 2>&1'"
reload_cmd = "/usr/local/bin/supervisorctl restart rabbitmq-server"