[template]
src   = "rabbitmq.config.tmpl"
dest  = "/etc/rabbitmq/rabbitmq.config"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "rabbitmq"
]
reload_cmd = "/bin/bash -c '/usr/local/bin/rabbitmq-reload 2>&1 | logger -t rabbitmq-reload[$$]' "
